FROMGIT: ASoC: Intel: Skylake: Re-order some code to silence a warning
I get a Smatch warning here:

    sound/soc/intel/skylake/skl-nhlt.c:335 skl_get_ssp_clks()
    error: testing array offset 'j' after use.

The code is harmless, but the checker is right that we should swap these
two conditions so we verify that the offset is within bounds before we
use it.

Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
Reviewed-by: Sriram Periyasamy <sriramx.periyasamy@intel.com>
Acked-by: Vinod Koul <vinod.koul@intel.com>
Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 87684d338a22d15e47b16ee68f569d74ad1d076e
https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git topic/intel)

BUG=b:71724897
TEST=With whole series applied + DSP Firmware and topology;
     audio playback and recording works on cnlrvp.

Change-Id: I1524f7ab831a792148253ce861ca730293c6e22e
Signed-off-by: Mike Mason <michael.w.mason@intel.com>